// ═══════════════════════════════════════════════════════════════════════════════
// Career Orientation & Work Environment Fit — Content Library
// مقياس الميول والتوجّه المهني
// ═══════════════════════════════════════════════════════════════════════════════

export const PRODUCT_INFO = {
  id: 'career_orientation',
  name_ar: 'مقياس الميول والتوجّه المهني',
  name_en: 'Career Orientation & Work Environment Fit',
  subtitle_ar: 'اكتشف المجالات المهنية التي تتوافق مع ميولك، قدراتك، قيمك ونقاط قوتك.',
  subtitle_en: 'Discover career fields that align with your interests, abilities, values, and strengths.',
  total_questions: 150,
  dimensions: 6,
  estimated_time: '40-45',
};

export const USER_STATUSES = {
  job_seeker: { ar: 'باحث عن عمل', en: 'Job Seeker' },
  student: { ar: 'طالب', en: 'Student' },
  career_changer: { ar: 'أفكر في تغيير مساري المهني', en: 'Considering Career Change' },
};

export const SECTIONS = [
  { id: 'riasec', name: { ar: 'الميول المهنية (RIASEC)', en: 'Occupational Interests (RIASEC)' }, questionCount: 60, icon: 'Compass' },
  { id: 'work_values', name: { ar: 'قيم العمل والتحفيزات', en: 'Work Values & Motivations' }, questionCount: 18, icon: 'Heart' },
  { id: 'skills', name: { ar: 'المهارات والقدرات', en: 'Skills & Abilities' }, questionCount: 19, icon: 'Zap' },
  { id: 'personality', name: { ar: 'الشخصية وأسلوب العمل', en: 'Personality & Work Style' }, questionCount: 25, icon: 'Users' },
  { id: 'strengths', name: { ar: 'نقاط القوة المهنية', en: 'Natural Professional Strengths' }, questionCount: 20, icon: 'Star' },
  { id: 'environment', name: { ar: 'تفضيلات بيئة العمل', en: 'Work Environment Preferences' }, questionCount: 8, icon: 'Building2' },
];

// ─── RIASEC TYPES ─────────────────────────────────────────────────────────────
export const RIASEC_TYPES = {
  R: {
    code: 'R', color: '#336fa3',
    name: { ar: 'واقعي', en: 'Realistic' },
    description: {
      ar: 'تفضل العمل العملي مع الأشياء والأدوات والآلات. تستمتع بالأنشطة البدنية والمهنية التي تتطلب مهارات يدوية وتقنية.',
      en: 'You prefer practical work with tools, machines, and objects. You enjoy physical and technical activities requiring manual skills.',
    },
    activities: { ar: ['تشغيل الآلات والأدوات', 'الإصلاح والصيانة', 'العمل في الهواء الطلق', 'البناء والتشييد'], en: ['Operating machinery', 'Repair and maintenance', 'Outdoor work', 'Construction'] },
    careers: { ar: ['المهندس', 'الفني', 'مدير العمليات', 'الميكانيكي'], en: ['Engineer', 'Technician', 'Operations Manager', 'Mechanic'] },
  },
  I: {
    code: 'I', color: '#05e1ae',
    name: { ar: 'استكشافي', en: 'Investigative' },
    description: {
      ar: 'تفضل العمل مع الأفكار والبيانات والتحليل. تستمتع بالبحث والاستكشاف وحل المشكلات المعقدة باستخدام المنطق والتفكير النقدي.',
      en: 'You prefer working with ideas, data, and analysis. You enjoy research, exploration, and solving complex problems using logic.',
    },
    activities: { ar: ['البحث العلمي', 'تحليل البيانات', 'إجراء التجارب', 'دراسة الظواهر'], en: ['Scientific research', 'Data analysis', 'Conducting experiments', 'Studying phenomena'] },
    careers: { ar: ['الباحث العلمي', 'محلل البيانات', 'الطبيب', 'المبرمج'], en: ['Research Scientist', 'Data Analyst', 'Physician', 'Software Developer'] },
  },
  A: {
    code: 'A', color: '#4ca9fa',
    name: { ar: 'فني / إبداعي', en: 'Artistic' },
    description: {
      ar: 'تفضل العمل مع الإبداع والتعبير الذاتي. تستمتع بالتصميم والكتابة والفنون وابتكار أفكار جديدة وحلول غير تقليدية.',
      en: 'You prefer creative work and self-expression. You enjoy design, writing, arts, and innovating new ideas and unconventional solutions.',
    },
    activities: { ar: ['التصميم الفني', 'الكتابة الإبداعية', 'التأليف والتلحين', 'التصوير'], en: ['Art design', 'Creative writing', 'Composing', 'Photography'] },
    careers: { ar: ['المصمم', 'الكاتب', 'المصور', 'مدير إبداعي'], en: ['Designer', 'Writer', 'Photographer', 'Creative Director'] },
  },
  S: {
    code: 'S', color: '#e8704a',
    name: { ar: 'اجتماعي', en: 'Social' },
    description: {
      ar: 'تفضل العمل مع الناس ومساعدتهم وتعليمهم. تستمتع بالتواصل والإرشاد وبناء العلاقات وتقديم الدعم للآخرين.',
      en: 'You prefer working with people, helping and teaching them. You enjoy communication, guidance, relationship-building, and supporting others.',
    },
    activities: { ar: ['التعليم والتدريب', 'الإرشاد والاستشارة', 'الرعاية الصحية', 'العمل التطوعي'], en: ['Teaching and training', 'Counseling', 'Healthcare', 'Volunteering'] },
    careers: { ar: ['المعلم', 'المستشار', 'الأخصائي الاجتماعي', 'مدير الموارد البشرية'], en: ['Teacher', 'Counselor', 'Social Worker', 'HR Manager'] },
  },
  E: {
    code: 'E', color: '#d4a017',
    name: { ar: 'مغامر / قيادي', en: 'Enterprising' },
    description: {
      ar: 'تفضل العمل القيادي وريادة الأعمال. تستمتع بإقناع الآخرين وإدارة المشاريع واتخاذ القرارات والمنافسة في بيئة الأعمال.',
      en: 'You prefer leadership and entrepreneurial work. You enjoy persuading others, managing projects, making decisions, and competing in business.',
    },
    activities: { ar: ['إدارة المشاريع', 'البيع والتسويق', 'التفاوض', 'ريادة الأعمال'], en: ['Project management', 'Sales and marketing', 'Negotiation', 'Entrepreneurship'] },
    careers: { ar: ['مدير المبيعات', 'رائد الأعمال', 'مدير التسويق', 'مستشار الإدارة'], en: ['Sales Manager', 'Entrepreneur', 'Marketing Manager', 'Management Consultant'] },
  },
  C: {
    code: 'C', color: '#6b7280',
    name: { ar: 'نظامي / مكتبي', en: 'Conventional' },
    description: {
      ar: 'تفضل العمل المنظم والمنهجي مع البيانات والسجلات. تستمتع بالتنظيم والترتيب واتباع الإجراءات وإدارة التفاصيل بدقة.',
      en: 'You prefer organized, systematic work with data and records. You enjoy organizing, following procedures, and managing details accurately.',
    },
    activities: { ar: ['تنظيم البيانات', 'إدارة السجلات', 'المحاسبة', 'إدخال البيانات'], en: ['Data organization', 'Records management', 'Accounting', 'Data entry'] },
    careers: { ar: ['المحاسب', 'محلل مالي', 'مدير مكتب', 'أخصائي الجودة'], en: ['Accountant', 'Financial Analyst', 'Office Manager', 'Quality Specialist'] },
  },
};

// ─── WORK VALUES ──────────────────────────────────────────────────────────────
export const WORK_VALUES = {
  achievement: {
    name: { ar: 'الإنجاز', en: 'Achievement' },
    description: { ar: 'الشعور بالتحقيق والإنجاز من خلال عمل ذي قيمة ونتائج ملموسة.', en: 'Feeling of accomplishment through valuable work with tangible results.' },
  },
  working_conditions: {
    name: { ar: 'ظروف العمل', en: 'Working Conditions' },
    description: { ar: 'العمل في بيئة آمنة ومريحة مع راتب ومزايا جيدة وثبات وظيفي.', en: 'Working in a safe, comfortable environment with good pay, benefits, and stability.' },
  },
  recognition: {
    name: { ar: 'التقدير', en: 'Recognition' },
    description: { ar: 'الحصول على تقدير لإنجازاتك وقيمة عملك من قبل الآخرين.', en: 'Receiving acknowledgment for your accomplishments and the value of your work.' },
  },
  relationships: {
    name: { ar: 'العلاقات', en: 'Relationships' },
    description: { ar: 'العمل مع زملاء ودودين في جو اجتماعي إيجابي وداعم.', en: 'Working with friendly colleagues in a positive, supportive social atmosphere.' },
  },
  support: {
    name: { ar: 'الدعم', en: 'Support' },
    description: { ar: 'الحصول على دعم من الإدارة وتوجيهات واضحة وفرص للتطور المهني.', en: 'Receiving management support, clear guidance, and professional development opportunities.' },
  },
  independence: {
    name: { ar: 'الاستقلالية', en: 'Independence' },
    description: { ar: 'الحرية في اتخاذ القرارات وتحديد أسلوب العمل والعمل بشكل مستقل.', en: 'Freedom to make decisions, determine work style, and work autonomously.' },
  },
};

// ─── SKILLS ───────────────────────────────────────────────────────────────────
export const SKILLS = {
  analytical: { name: { ar: 'التفكير التحليلي', en: 'Analytical Thinking' }, description: { ar: 'قدرة على تحليل المعلومات وبيانات واستخلاص الاستنتاجات.', en: 'Ability to analyze information and draw logical conclusions.' } },
  communication: { name: { ar: 'التواصل', en: 'Communication' }, description: { ar: 'قدرة على التواصل الفعّال كتابياً وشفهياً مع الآخرين.', en: 'Ability to communicate effectively in writing and speech.' } },
  organization: { name: { ar: 'التنظيم والتنفيذ', en: 'Organization & Execution' }, description: { ar: 'قدرة على تنظيم المهام وإدارتها وإنجازها بكفاءة.', en: 'Ability to organize, manage, and complete tasks efficiently.' } },
  digital_learning: { name: { ar: 'الكفاءة الرقمية والتعلم', en: 'Digital & Learning Agility' }, description: { ar: 'قدرة على استخدام التقنيات وتعلم مهارات جديدة بسرعة.', en: 'Ability to use technology and learn new skills quickly.' } },
  collaboration: { name: { ar: 'التعاون والتأثير', en: 'Collaboration & Influence' }, description: { ar: 'قدرة على العمل ضمن فريق والتأثير في الآخرين إيجابياً.', en: 'Ability to work in teams and positively influence others.' } },
  creativity: { name: { ar: 'الإبداع وحل المشكلات', en: 'Creativity & Problem Solving' }, description: { ar: 'قدرة على ابتكار حلول جديدة وحل المشكلات بطرق مبتكرة.', en: 'Ability to innovate solutions and solve problems creatively.' } },
};

// ─── PERSONALITY AXES ─────────────────────────────────────────────────────────
export const PERSONALITY_AXES = {
  structured_flexible: {
    name: { ar: 'منظم مقابل مرن', en: 'Structured vs Flexible' },
    left: { ar: 'منظم', en: 'Structured' }, right: { ar: 'مرن', en: 'Flexible' },
    description: { ar: 'تفضل العمل وفق جداول وإجراءات واضحة أم تفضل المرونة والتكيف.', en: 'Prefer clear schedules and procedures or flexibility and adaptation.' },
  },
  detail_bigpicture: {
    name: { ar: 'تفصيلي مقابل شمولي', en: 'Detail vs Big-Picture' },
    left: { ar: 'تركيز على التفاصيل', en: 'Detail-Focused' }, right: { ar: 'رؤية شاملة', en: 'Big-Picture' },
    description: { ar: 'تركز على التفاصيل الدقيقة أم على الصورة الكبرى والاستراتيجية.', en: 'Focus on fine details or on the big picture and strategy.' },
  },
  independent_collaborative: {
    name: { ar: 'مستقل مقابل تعاوني', en: 'Independent vs Collaborative' },
    left: { ar: 'مستقل', en: 'Independent' }, right: { ar: 'تعاوني', en: 'Collaborative' },
    description: { ar: 'تفضل العمل بمفردك أم ضمن فريق ومجموعة.', en: 'Prefer working alone or within a team and group.' },
  },
  reflective_fast: {
    name: { ar: 'تأملي مقابل سريع', en: 'Reflective vs Fast-Acting' },
    left: { ar: 'تأملي', en: 'Reflective' }, right: { ar: 'سريع القرار', en: 'Fast-Acting' },
    description: { ar: 'تأخذ وقتك في التفكير أم تتخذ القرارات بسرعة وثقة.', en: 'Take time to reflect or make decisions quickly and confidently.' },
  },
  stability_novelty: {
    name: { ar: 'ثبات مقابل تنوع', en: 'Stability vs Novelty' },
    left: { ar: 'ثبات واستقرار', en: 'Stability' }, right: { ar: 'تنوع وتجديد', en: 'Novelty' },
    description: { ar: 'تفضل الروتين والثبات أم التنوع والتجديد المستمر.', en: 'Prefer routine and stability or variety and constant change.' },
  },
};

// ─── STRENGTHS ────────────────────────────────────────────────────────────────
export const STRENGTHS = {
  thinking_learning: { name: { ar: 'التفكير والتعلم', en: 'Thinking & Learning' }, description: { ar: 'القدرة على التعلم المستمر والتفكير العميق والاستيعاب السريع.', en: 'Continuous learning, deep thinking, and quick comprehension.' } },
  achievement_perseverance: { name: { ar: 'الإنجاز والمثابرة', en: 'Achievement & Perseverance' }, description: { ar: 'القدرة على الإنجاز والمثابرة أمام التحديات وتحقيق الأهداف.', en: 'Ability to achieve, persevere through challenges, and reach goals.' } },
  influence_leadership: { name: { ar: 'التأثير والقيادة', en: 'Influence & Leadership' }, description: { ar: 'القدرة على التأثير في الآخرين وقيادتهم نحو الأهداف.', en: 'Ability to influence others and lead them toward goals.' } },
  relationships_cooperation: { name: { ar: 'العلاقات والتعاون', en: 'Relationships & Cooperation' }, description: { ar: 'القدرة على بناء العلاقات والتعاون الفعّال مع الآخرين.', en: 'Ability to build relationships and cooperate effectively with others.' } },
  self_management: { name: { ar: 'إدارة الذات والمرونة', en: 'Self-Management & Resilience' }, description: { ar: 'القدرة على إدارة الذات والتعافي من الضغوط والصمود.', en: 'Ability to self-manage, recover from stress, and remain resilient.' } },
};

// ─── ENVIRONMENT AXES ──────────────────────────────────────────────────────────
export const ENVIRONMENT_AXES = {
  indoor_outdoor: { name: { ar: 'داخلي مقابل خارجي', en: 'Indoor vs Outdoor' }, left: { ar: 'داخلي', en: 'Indoor' }, right: { ar: 'خارجي', en: 'Outdoor' } },
  team_solo: { name: { ar: 'فريق مقابل فردي', en: 'Team vs Solo' }, left: { ar: 'فريق', en: 'Team' }, right: { ar: 'فردي', en: 'Solo' } },
  structured_flexible_env: { name: { ar: 'منظم مقابل مرن', en: 'Structured vs Flexible' }, left: { ar: 'منظم', en: 'Structured' }, right: { ar: 'مرن', en: 'Flexible' } },
  quiet_active: { name: { ar: 'هادئ مقابل نشط', en: 'Quiet vs Active' }, left: { ar: 'هادئ', en: 'Quiet' }, right: { ar: 'نشط', en: 'Active' } },
  office_remote: { name: { ar: 'مكتبي مقابل عن بُعد', en: 'Office vs Remote' }, left: { ar: 'مكتبي', en: 'Office' }, right: { ar: 'عن بُعد', en: 'Remote' } },
  technical_social: { name: { ar: 'تقني مقابل اجتماعي', en: 'Technical vs Social' }, left: { ar: 'تقني', en: 'Technical' }, right: { ar: 'اجتماعي', en: 'Social' } },
  routine_varied: { name: { ar: 'روتيني مقابل متنوع', en: 'Routine vs Varied' }, left: { ar: 'روتيني', en: 'Routine' }, right: { ar: 'متنوع', en: 'Varied' } },
  high_low_pressure: { name: { ar: 'ضغط عالٍ مقابل ضغط منخفض', en: 'High vs Low Pressure' }, left: { ar: 'ضغط عالٍ', en: 'High Pressure' }, right: { ar: 'ضغط منخفض', en: 'Low Pressure' } },
};

// ─── OCCUPATION PROFILES ──────────────────────────────────────────────────────
// Reviewed structured profiles — NOT AI-generated. Vectors are admin-approved.
export const OCCUPATIONS = [
  {
    id: 'software_dev', title_ar: 'مطور برمجيات', title_en: 'Software Developer',
    family_ar: 'تقنية المعلومات', family_en: 'Information Technology',
    riasec: { R: 0.2, I: 0.9, A: 0.4, S: 0.1, E: 0.2, C: 0.3 },
    work_values: { achievement: 0.8, working_conditions: 0.7, recognition: 0.6, relationships: 0.4, support: 0.5, independence: 0.8 },
    skills: { analytical: 0.9, communication: 0.5, organization: 0.7, digital_learning: 0.95, collaboration: 0.5, creativity: 0.7 },
    strengths: { thinking_learning: 0.9, achievement_perseverance: 0.7, influence_leadership: 0.3, relationships_cooperation: 0.4, self_management: 0.7 },
    work_style: { structured_flexible: 0.4, detail_bigpicture: 0.5, independent_collaborative: 0.3, reflective_fast: 0.3, stability_novelty: 0.7 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.4, structured_flexible_env: 0.3, quiet_active: 0.3, office_remote: 0.8, technical_social: 0.2, routine_varied: 0.7, high_low_pressure: 0.6 },
    education_ar: 'بكالوريوس علوم حاسب أو ما يعادله', education_en: 'Bachelor in Computer Science or equivalent',
    tasks_ar: ['كتابة وتطوير الأكواد البرمجية', 'اختبار وتصحيح البرامج', 'التعاون مع الفريق لتطوير المنتجات', 'حل المشكلات التقنية'],
    tasks_en: ['Writing and developing code', 'Testing and debugging software', 'Collaborating with team on product development', 'Solving technical problems'],
    pathways_ar: ['دراسة علوم الحاسب أو هندسة البرمجيات', 'بناء مشاريع عملية على GitHub', 'التدريب في شركات التقنية'],
    pathways_en: ['Study computer science or software engineering', 'Build practical projects on GitHub', 'Intern at tech companies'],
    related: ['data_analyst', 'it_support', 'systems_analyst'],
  },
  {
    id: 'data_analyst', title_ar: 'محلل بيانات', title_en: 'Data Analyst',
    family_ar: 'تقنية المعلومات', family_en: 'Information Technology',
    riasec: { R: 0.1, I: 0.9, A: 0.2, S: 0.2, E: 0.3, C: 0.7 },
    work_values: { achievement: 0.7, working_conditions: 0.7, recognition: 0.5, relationships: 0.4, support: 0.5, independence: 0.7 },
    skills: { analytical: 0.95, communication: 0.6, organization: 0.8, digital_learning: 0.85, collaboration: 0.5, creativity: 0.5 },
    strengths: { thinking_learning: 0.85, achievement_perseverance: 0.7, influence_leadership: 0.3, relationships_cooperation: 0.4, self_management: 0.7 },
    work_style: { structured_flexible: 0.7, detail_bigpicture: 0.3, independent_collaborative: 0.4, reflective_fast: 0.4, stability_novelty: 0.5 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.4, structured_flexible_env: 0.6, quiet_active: 0.3, office_remote: 0.7, technical_social: 0.3, routine_varied: 0.5, high_low_pressure: 0.5 },
    education_ar: 'بكالوريوس في إحصاء أو علوم بيانات', education_en: 'Bachelor in Statistics or Data Science',
    tasks_ar: ['تحليل البيانات واستخلاص الرؤى', 'بناء لوحات المعلومات والتقارير', 'استخدام أدوات تحليل البيانات', 'تقديم التوصيات للإدارة'],
    tasks_en: ['Analyzing data and extracting insights', 'Building dashboards and reports', 'Using data analysis tools', 'Presenting recommendations to management'],
    pathways_ar: ['دراسة الإحصاء أو علوم البيانات', 'تعلم SQL و Python و Power BI', 'بناء مشاريع تحليل بيانات'],
    pathways_en: ['Study statistics or data science', 'Learn SQL, Python, and Power BI', 'Build data analysis projects'],
    related: ['software_dev', 'financial_analyst', 'systems_analyst'],
  },
  {
    id: 'graphic_designer', title_ar: 'مصمم جرافيك', title_en: 'Graphic Designer',
    family_ar: 'التصميم والإبداع', family_en: 'Design & Creative',
    riasec: { R: 0.2, I: 0.2, A: 0.95, S: 0.3, E: 0.4, C: 0.2 },
    work_values: { achievement: 0.7, working_conditions: 0.6, recognition: 0.8, relationships: 0.5, support: 0.5, independence: 0.8 },
    skills: { analytical: 0.4, communication: 0.6, organization: 0.5, digital_learning: 0.7, collaboration: 0.6, creativity: 0.95 },
    strengths: { thinking_learning: 0.6, achievement_perseverance: 0.6, influence_leadership: 0.4, relationships_cooperation: 0.5, self_management: 0.6 },
    work_style: { structured_flexible: 0.8, detail_bigpicture: 0.6, independent_collaborative: 0.4, reflective_fast: 0.5, stability_novelty: 0.8 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.5, structured_flexible_env: 0.7, quiet_active: 0.4, office_remote: 0.8, technical_social: 0.4, routine_varied: 0.8, high_low_pressure: 0.5 },
    education_ar: 'بكالوريوس في التصميم الجرافيكي أو ما يعادله', education_en: 'Bachelor in Graphic Design or equivalent',
    tasks_ar: ['تصميم الهويات البصرية', 'إنشاء المحتوى البصري', 'التعاون مع فرق التسويق', 'تطوير مفاهيم إبداعية'],
    tasks_en: ['Designing visual identities', 'Creating visual content', 'Collaborating with marketing teams', 'Developing creative concepts'],
    pathways_ar: ['دراسة التصميم الجرافيكي', 'بناء معرض أعمال قوي', 'تعلم Adobe Creative Suite'],
    pathways_en: ['Study graphic design', 'Build a strong portfolio', 'Learn Adobe Creative Suite'],
    related: ['marketing_specialist', 'content_creator', 'ux_designer'],
  },
  {
    id: 'teacher', title_ar: 'معلم / مدرس', title_en: 'Teacher / Educator',
    family_ar: 'التعليم والتدريب', family_en: 'Education & Training',
    riasec: { R: 0.1, I: 0.4, A: 0.4, S: 0.95, E: 0.5, C: 0.4 },
    work_values: { achievement: 0.7, working_conditions: 0.6, recognition: 0.6, relationships: 0.8, support: 0.7, independence: 0.6 },
    skills: { analytical: 0.5, communication: 0.9, organization: 0.7, digital_learning: 0.6, collaboration: 0.8, creativity: 0.7 },
    strengths: { thinking_learning: 0.7, achievement_perseverance: 0.7, influence_leadership: 0.7, relationships_cooperation: 0.9, self_management: 0.7 },
    work_style: { structured_flexible: 0.6, detail_bigpicture: 0.5, independent_collaborative: 0.6, reflective_fast: 0.5, stability_novelty: 0.5 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.7, structured_flexible_env: 0.6, quiet_active: 0.6, office_remote: 0.3, technical_social: 0.8, routine_varied: 0.5, high_low_pressure: 0.4 },
    education_ar: 'بكالوريوس في التخصص مع إجازة تعليم', education_en: "Bachelor's degree with teaching certification",
    tasks_ar: ['تخطيط وتقديم الدروس', 'تقييم تقدم الطلاب', 'إدارة الصف والبيئة التعليمية', 'التواصل مع أولياء الأمور'],
    tasks_en: ['Planning and delivering lessons', 'Assessing student progress', 'Managing classroom environment', 'Communicating with parents'],
    pathways_ar: ['الحصول على مؤهل تعليمي', 'اكتساب خبرة في التدريس', 'تطوير مهارات التواصل'],
    pathways_en: ['Obtain teaching qualification', 'Gain teaching experience', 'Develop communication skills'],
    related: ['hr_specialist', 'social_worker', 'trainer'],
  },
  {
    id: 'sales_manager', title_ar: 'مدير مبيعات', title_en: 'Sales Manager',
    family_ar: 'المبيعات والأعمال', family_en: 'Sales & Business',
    riasec: { R: 0.2, I: 0.3, A: 0.3, S: 0.6, E: 0.95, C: 0.4 },
    work_values: { achievement: 0.9, working_conditions: 0.6, recognition: 0.8, relationships: 0.7, support: 0.5, independence: 0.7 },
    skills: { analytical: 0.6, communication: 0.9, organization: 0.7, digital_learning: 0.5, collaboration: 0.85, creativity: 0.6 },
    strengths: { thinking_learning: 0.6, achievement_perseverance: 0.9, influence_leadership: 0.9, relationships_cooperation: 0.85, self_management: 0.8 },
    work_style: { structured_flexible: 0.5, detail_bigpicture: 0.7, independent_collaborative: 0.7, reflective_fast: 0.7, stability_novelty: 0.6 },
    environment: { indoor_outdoor: 0.3, team_solo: 0.8, structured_flexible_env: 0.4, quiet_active: 0.8, office_remote: 0.3, technical_social: 0.8, routine_varied: 0.8, high_low_pressure: 0.8 },
    education_ar: 'بكالوريوس في إدارة الأعمال أو التسويق', education_en: 'Bachelor in Business Administration or Marketing',
    tasks_ar: ['إدارة فريق المبيعات', 'وضع استراتيجيات البيع', 'بناء علاقات العملاء', 'تحقيق أهداف الإيرادات'],
    tasks_en: ['Managing sales team', 'Setting sales strategies', 'Building customer relationships', 'Achieving revenue targets'],
    pathways_ar: ['دراسة إدارة الأعمال', 'اكتساب خبرة في المبيعات', 'تطوير مهارات القيادة'],
    pathways_en: ['Study business administration', 'Gain sales experience', 'Develop leadership skills'],
    related: ['marketing_specialist', 'entrepreneur', 'management_consultant'],
  },
  {
    id: 'accountant', title_ar: 'محاسب', title_en: 'Accountant',
    family_ar: 'المالية والمحاسبة', family_en: 'Finance & Accounting',
    riasec: { R: 0.1, I: 0.4, A: 0.1, S: 0.2, E: 0.3, C: 0.95 },
    work_values: { achievement: 0.6, working_conditions: 0.8, recognition: 0.5, relationships: 0.4, support: 0.6, independence: 0.5 },
    skills: { analytical: 0.8, communication: 0.5, organization: 0.9, digital_learning: 0.6, collaboration: 0.4, creativity: 0.3 },
    strengths: { thinking_learning: 0.7, achievement_perseverance: 0.7, influence_leadership: 0.3, relationships_cooperation: 0.4, self_management: 0.8 },
    work_style: { structured_flexible: 0.2, detail_bigpicture: 0.2, independent_collaborative: 0.4, reflective_fast: 0.4, stability_novelty: 0.2 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.4, structured_flexible_env: 0.2, quiet_active: 0.2, office_remote: 0.5, technical_social: 0.3, routine_varied: 0.2, high_low_pressure: 0.5 },
    education_ar: 'بكالوريوس في المحاسبة أو المالية', education_en: "Bachelor in Accounting or Finance",
    tasks_ar: ['إعداد القوائم المالية', 'مراجعة وتدقيق الحسابات', 'إعداد التقارير المالية', 'ضمان الامتثال الضريبي'],
    tasks_en: ['Preparing financial statements', 'Auditing accounts', 'Preparing financial reports', 'Ensuring tax compliance'],
    pathways_ar: ['دراسة المحاسبة', 'الحصول على شهادة مهنية', 'اكتساب خبرة في المراجعة'],
    pathways_en: ['Study accounting', 'Obtain professional certification', 'Gain auditing experience'],
    related: ['financial_analyst', 'auditor', 'office_manager'],
  },
  {
    id: 'engineer', title_ar: 'مهندس', title_en: 'Engineer',
    family_ar: 'الهندسة', family_en: 'Engineering',
    riasec: { R: 0.85, I: 0.8, A: 0.3, S: 0.2, E: 0.4, C: 0.6 },
    work_values: { achievement: 0.8, working_conditions: 0.7, recognition: 0.7, relationships: 0.5, support: 0.5, independence: 0.6 },
    skills: { analytical: 0.9, communication: 0.6, organization: 0.8, digital_learning: 0.8, collaboration: 0.7, creativity: 0.7 },
    strengths: { thinking_learning: 0.85, achievement_perseverance: 0.8, influence_leadership: 0.5, relationships_cooperation: 0.6, self_management: 0.7 },
    work_style: { structured_flexible: 0.4, detail_bigpicture: 0.4, independent_collaborative: 0.5, reflective_fast: 0.4, stability_novelty: 0.5 },
    environment: { indoor_outdoor: 0.5, team_solo: 0.6, structured_flexible_env: 0.4, quiet_active: 0.5, office_remote: 0.3, technical_social: 0.3, routine_varied: 0.6, high_low_pressure: 0.6 },
    education_ar: 'بكالوريوس في الهندسة (تخصص دقيق)', education_en: "Bachelor's in Engineering (specific discipline)",
    tasks_ar: ['تصميم وتطوير الأنظمة', 'حل المشكلات الهندسية', 'إدارة المشاريع التقنية', 'ضمان الجودة والسلامة'],
    tasks_en: ['Designing and developing systems', 'Solving engineering problems', 'Managing technical projects', 'Ensuring quality and safety'],
    pathways_ar: ['دراسة الهندسة', 'الحصول على ترخيص مهني', 'اكتساب خبرة عملية'],
    pathways_en: ['Study engineering', 'Obtain professional license', 'Gain practical experience'],
    related: ['architect', 'project_manager', 'software_dev'],
  },
  {
    id: 'nurse', title_ar: 'ممرض / أخصائي صحي', title_en: 'Nurse / Healthcare Specialist',
    family_ar: 'الرعاية الصحية', family_en: 'Healthcare',
    riasec: { R: 0.4, I: 0.5, A: 0.2, S: 0.9, E: 0.3, C: 0.5 },
    work_values: { achievement: 0.7, working_conditions: 0.5, recognition: 0.6, relationships: 0.8, support: 0.7, independence: 0.4 },
    skills: { analytical: 0.6, communication: 0.85, organization: 0.8, digital_learning: 0.6, collaboration: 0.85, creativity: 0.4 },
    strengths: { thinking_learning: 0.6, achievement_perseverance: 0.8, influence_leadership: 0.5, relationships_cooperation: 0.9, self_management: 0.8 },
    work_style: { structured_flexible: 0.3, detail_bigpicture: 0.3, independent_collaborative: 0.7, reflective_fast: 0.6, stability_novelty: 0.4 },
    environment: { indoor_outdoor: 0.2, team_solo: 0.8, structured_flexible_env: 0.3, quiet_active: 0.8, office_remote: 0.1, technical_social: 0.7, routine_varied: 0.7, high_low_pressure: 0.8 },
    education_ar: 'بكالوريوس في التمريض أو العلوم الصحية', education_en: "Bachelor in Nursing or Health Sciences",
    tasks_ar: ['رعاية المرضى', 'مراقبة الحالة الصحية', 'إعطاء العلاجات', 'التواصل مع الفريق الطبي'],
    tasks_en: ['Patient care', 'Monitoring health status', 'Administering treatments', 'Communicating with medical team'],
    pathways_ar: ['دراسة التمريض', 'الحصول على ترخيص مهني', 'اكتساب خبرة سريرية'],
    pathways_en: ['Study nursing', 'Obtain professional license', 'Gain clinical experience'],
    related: ['teacher', 'social_worker', 'counselor'],
  },
  {
    id: 'marketing_specialist', title_ar: 'أخصائي تسويق', title_en: 'Marketing Specialist',
    family_ar: 'التسويق', family_en: 'Marketing',
    riasec: { R: 0.1, I: 0.4, A: 0.7, S: 0.5, E: 0.85, C: 0.4 },
    work_values: { achievement: 0.8, working_conditions: 0.6, recognition: 0.7, relationships: 0.6, support: 0.5, independence: 0.7 },
    skills: { analytical: 0.7, communication: 0.85, organization: 0.7, digital_learning: 0.8, collaboration: 0.75, creativity: 0.85 },
    strengths: { thinking_learning: 0.7, achievement_perseverance: 0.7, influence_leadership: 0.7, relationships_cooperation: 0.7, self_management: 0.7 },
    work_style: { structured_flexible: 0.6, detail_bigpicture: 0.7, independent_collaborative: 0.6, reflective_fast: 0.6, stability_novelty: 0.7 },
    environment: { indoor_outdoor: 0.2, team_solo: 0.7, structured_flexible_env: 0.5, quiet_active: 0.6, office_remote: 0.6, technical_social: 0.6, routine_varied: 0.8, high_low_pressure: 0.6 },
    education_ar: 'بكالوريوس في التسويق أو إدارة الأعمال', education_en: 'Bachelor in Marketing or Business Administration',
    tasks_ar: ['تطوير استراتيجيات التسويق', 'إدارة الحملات الإعلانية', 'تحليل السوق والمنافسين', 'إنشاء المحتوى التسويقي'],
    tasks_en: ['Developing marketing strategies', 'Managing advertising campaigns', 'Analyzing market and competitors', 'Creating marketing content'],
    pathways_ar: ['دراسة التسويق', 'بناء خبرة في التسويق الرقمي', 'تطوير مهارات التحليل'],
    pathways_en: ['Study marketing', 'Build digital marketing experience', 'Develop analytical skills'],
    related: ['graphic_designer', 'sales_manager', 'content_creator'],
  },
  {
    id: 'hr_specialist', title_ar: 'أخصائي موارد بشرية', title_en: 'HR Specialist',
    family_ar: 'الموارد البشرية', family_en: 'Human Resources',
    riasec: { R: 0.1, I: 0.3, A: 0.2, S: 0.85, E: 0.5, C: 0.6 },
    work_values: { achievement: 0.6, working_conditions: 0.7, recognition: 0.5, relationships: 0.8, support: 0.7, independence: 0.5 },
    skills: { analytical: 0.6, communication: 0.9, organization: 0.8, digital_learning: 0.6, collaboration: 0.85, creativity: 0.5 },
    strengths: { thinking_learning: 0.6, achievement_perseverance: 0.6, influence_leadership: 0.6, relationships_cooperation: 0.9, self_management: 0.7 },
    work_style: { structured_flexible: 0.5, detail_bigpicture: 0.5, independent_collaborative: 0.7, reflective_fast: 0.5, stability_novelty: 0.4 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.7, structured_flexible_env: 0.5, quiet_active: 0.5, office_remote: 0.4, technical_social: 0.8, routine_varied: 0.5, high_low_pressure: 0.5 },
    education_ar: 'بكالوريوس في إدارة الموارد البشرية أو الأعمال', education_en: 'Bachelor in HR Management or Business',
    tasks_ar: ['إدارة التوظيف والاختيار', 'تطوير سياسات الموظفين', 'إدارة التدريب والتطوير', 'حل النزاعات في العمل'],
    tasks_en: ['Managing recruitment and selection', 'Developing employee policies', 'Managing training and development', 'Resolving workplace conflicts'],
    pathways_ar: ['دراسة إدارة الموارد البشرية', 'اكتساب شهادات مهنية', 'تطوير مهارات التواصل'],
    pathways_en: ['Study HR management', 'Gain professional certifications', 'Develop communication skills'],
    related: ['teacher', 'office_manager', 'trainer'],
  },
  {
    id: 'research_scientist', title_ar: 'باحث علمي', title_en: 'Research Scientist',
    family_ar: 'البحث العلمي', family_en: 'Scientific Research',
    riasec: { R: 0.3, I: 0.95, A: 0.4, S: 0.3, E: 0.2, C: 0.5 },
    work_values: { achievement: 0.8, working_conditions: 0.6, recognition: 0.7, relationships: 0.5, support: 0.6, independence: 0.8 },
    skills: { analytical: 0.95, communication: 0.7, organization: 0.8, digital_learning: 0.85, collaboration: 0.6, creativity: 0.8 },
    strengths: { thinking_learning: 0.95, achievement_perseverance: 0.85, influence_leadership: 0.4, relationships_cooperation: 0.5, self_management: 0.8 },
    work_style: { structured_flexible: 0.5, detail_bigpicture: 0.4, independent_collaborative: 0.4, reflective_fast: 0.2, stability_novelty: 0.7 },
    environment: { indoor_outdoor: 0.3, team_solo: 0.5, structured_flexible_env: 0.5, quiet_active: 0.3, office_remote: 0.5, technical_social: 0.3, routine_varied: 0.6, high_low_pressure: 0.4 },
    education_ar: 'دكتوراه أو ماجستير في التخصص العلمي', education_en: 'PhD or Masters in scientific field',
    tasks_ar: ['تصميم وإجراء التجارب', 'نشر الأبحاث العلمية', 'تحليل البيانات البحثية', 'كتابة المقترحات البحثية'],
    tasks_en: ['Designing and conducting experiments', 'Publishing scientific research', 'Analyzing research data', 'Writing research proposals'],
    pathways_ar: ['دراسة العلوم حتى الدكتوراه', 'نشر أبحاث في مجلات محكمة', 'العمل في مراكز الأبحاث'],
    pathways_en: ['Study science to PhD level', 'Publish in peer-reviewed journals', 'Work in research centers'],
    related: ['data_analyst', 'software_dev', 'professor'],
  },
  {
    id: 'project_manager', title_ar: 'مدير مشاريع', title_en: 'Project Manager',
    family_ar: 'إدارة المشاريع', family_en: 'Project Management',
    riasec: { R: 0.3, I: 0.4, A: 0.3, S: 0.5, E: 0.8, C: 0.7 },
    work_values: { achievement: 0.85, working_conditions: 0.6, recognition: 0.7, relationships: 0.7, support: 0.5, independence: 0.6 },
    skills: { analytical: 0.8, communication: 0.85, organization: 0.9, digital_learning: 0.7, collaboration: 0.85, creativity: 0.6 },
    strengths: { thinking_learning: 0.7, achievement_perseverance: 0.85, influence_leadership: 0.85, relationships_cooperation: 0.85, self_management: 0.85 },
    work_style: { structured_flexible: 0.4, detail_bigpicture: 0.6, independent_collaborative: 0.7, reflective_fast: 0.6, stability_novelty: 0.6 },
    environment: { indoor_outdoor: 0.2, team_solo: 0.8, structured_flexible_env: 0.4, quiet_active: 0.7, office_remote: 0.5, technical_social: 0.5, routine_varied: 0.7, high_low_pressure: 0.7 },
    education_ar: 'بكالوريوس مع شهادة PMP أو ما يعادلها', education_en: "Bachelor's with PMP or equivalent certification",
    tasks_ar: ['تخطيط وإدارة المشاريع', 'تنسيق فرق العمل', 'إدارة الميزانيات والجداول', 'ضمان تسليم المشروع'],
    tasks_en: ['Planning and managing projects', 'Coordinating teams', 'Managing budgets and schedules', 'Ensuring project delivery'],
    pathways_ar: ['اكتساب شهادة PMP', 'تطوير مهارات القيادة', 'بناء خبرة في إدارة المشاريع'],
    pathways_en: ['Obtain PMP certification', 'Develop leadership skills', 'Build project management experience'],
    related: ['management_consultant', 'engineer', 'sales_manager'],
  },
  {
    id: 'content_creator', title_ar: 'صانع محتوى / كاتب', title_en: 'Content Creator / Writer',
    family_ar: 'الإعلام والمحتوى', family_en: 'Media & Content',
    riasec: { R: 0.1, I: 0.4, A: 0.9, S: 0.5, E: 0.5, C: 0.3 },
    work_values: { achievement: 0.7, working_conditions: 0.6, recognition: 0.8, relationships: 0.5, support: 0.4, independence: 0.85 },
    skills: { analytical: 0.5, communication: 0.9, organization: 0.6, digital_learning: 0.75, collaboration: 0.5, creativity: 0.9 },
    strengths: { thinking_learning: 0.7, achievement_perseverance: 0.7, influence_leadership: 0.5, relationships_cooperation: 0.5, self_management: 0.75 },
    work_style: { structured_flexible: 0.8, detail_bigpicture: 0.6, independent_collaborative: 0.3, reflective_fast: 0.4, stability_novelty: 0.8 },
    environment: { indoor_outdoor: 0.2, team_solo: 0.3, structured_flexible_env: 0.7, quiet_active: 0.4, office_remote: 0.9, technical_social: 0.4, routine_varied: 0.8, high_low_pressure: 0.4 },
    education_ar: 'بكالوريوس في الإعلام أو الأدب أو ما يعادله', education_en: 'Bachelor in Media, Literature, or equivalent',
    tasks_ar: ['كتابة وتحرير المحتوى', 'إنشاء محتوى للمنصات الرقمية', 'تطوير الأفكار الإبداعية', 'التعاون مع فرق الإنتاج'],
    tasks_en: ['Writing and editing content', 'Creating digital platform content', 'Developing creative ideas', 'Collaborating with production teams'],
    pathways_ar: ['دراسة الإعلام أو الكتابة', 'بناء معرض أعمال كتابي', 'تطوير مهارات الكتابة الرقمية'],
    pathways_en: ['Study media or writing', 'Build a writing portfolio', 'Develop digital writing skills'],
    related: ['graphic_designer', 'marketing_specialist', 'teacher'],
  },
  {
    id: 'it_support', title_ar: 'أخصائي دعم تقني', title_en: 'IT Support Specialist',
    family_ar: 'تقنية المعلومات', family_en: 'Information Technology',
    riasec: { R: 0.5, I: 0.7, A: 0.2, S: 0.5, E: 0.3, C: 0.7 },
    work_values: { achievement: 0.6, working_conditions: 0.7, recognition: 0.5, relationships: 0.6, support: 0.6, independence: 0.5 },
    skills: { analytical: 0.75, communication: 0.75, organization: 0.7, digital_learning: 0.85, collaboration: 0.7, creativity: 0.5 },
    strengths: { thinking_learning: 0.75, achievement_perseverance: 0.6, influence_leadership: 0.4, relationships_cooperation: 0.7, self_management: 0.7 },
    work_style: { structured_flexible: 0.5, detail_bigpicture: 0.4, independent_collaborative: 0.6, reflective_fast: 0.6, stability_novelty: 0.5 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.6, structured_flexible_env: 0.5, quiet_active: 0.5, office_remote: 0.6, technical_social: 0.5, routine_varied: 0.6, high_low_pressure: 0.6 },
    education_ar: 'بكالوريوس في تقنية المعلومات أو شهادات مهنية', education_en: "Bachelor in IT or professional certifications",
    tasks_ar: ['دعم المستخدمين تقنياً', 'صيانة الأنظمة والشبكات', 'حل المشكلات التقنية', 'تثبيت وتحديث البرمجيات'],
    tasks_en: ['Providing technical user support', 'Maintaining systems and networks', 'Solving technical problems', 'Installing and updating software'],
    pathways_ar: ['دراسة تقنية المعلومات', 'الحصول على شهادات مثل CompTIA', 'اكتساب خبرة في الدعم التقني'],
    pathways_en: ['Study IT', 'Obtain certifications like CompTIA', 'Gain tech support experience'],
    related: ['software_dev', 'systems_analyst', 'data_analyst'],
  },
  {
    id: 'social_worker', title_ar: 'أخصائي اجتماعي', title_en: 'Social Worker',
    family_ar: 'الخدمات الاجتماعية', family_en: 'Social Services',
    riasec: { R: 0.2, I: 0.3, A: 0.3, S: 0.95, E: 0.4, C: 0.4 },
    work_values: { achievement: 0.7, working_conditions: 0.5, recognition: 0.5, relationships: 0.9, support: 0.7, independence: 0.5 },
    skills: { analytical: 0.5, communication: 0.9, organization: 0.7, digital_learning: 0.5, collaboration: 0.85, creativity: 0.5 },
    strengths: { thinking_learning: 0.6, achievement_perseverance: 0.75, influence_leadership: 0.5, relationships_cooperation: 0.95, self_management: 0.8 },
    work_style: { structured_flexible: 0.5, detail_bigpicture: 0.6, independent_collaborative: 0.7, reflective_fast: 0.5, stability_novelty: 0.5 },
    environment: { indoor_outdoor: 0.4, team_solo: 0.7, structured_flexible_env: 0.5, quiet_active: 0.6, office_remote: 0.2, technical_social: 0.8, routine_varied: 0.7, high_low_pressure: 0.6 },
    education_ar: 'بكالوريوس في الخدمة الاجتماعية', education_en: "Bachelor in Social Work",
    tasks_ar: ['تقديم الدعم للأفراد والأسر', 'تقييم الاحتياجات الاجتماعية', 'ربط العملاء بالخدمات', 'متابعة الحالات'],
    tasks_en: ['Supporting individuals and families', 'Assessing social needs', 'Connecting clients to services', 'Following up on cases'],
    pathways_ar: ['دراسة الخدمة الاجتماعية', 'اكتساب خبرة ميدانية', 'تطوير مهارات الاستشارة'],
    pathways_en: ['Study social work', 'Gain field experience', 'Develop counseling skills'],
    related: ['nurse', 'counselor', 'teacher'],
  },
  {
    id: 'financial_analyst', title_ar: 'محلل مالي', title_en: 'Financial Analyst',
    family_ar: 'المالية', family_en: 'Finance',
    riasec: { R: 0.1, I: 0.8, A: 0.2, S: 0.3, E: 0.6, C: 0.85 },
    work_values: { achievement: 0.8, working_conditions: 0.7, recognition: 0.6, relationships: 0.5, support: 0.5, independence: 0.6 },
    skills: { analytical: 0.9, communication: 0.7, organization: 0.8, digital_learning: 0.75, collaboration: 0.6, creativity: 0.4 },
    strengths: { thinking_learning: 0.8, achievement_perseverance: 0.75, influence_leadership: 0.5, relationships_cooperation: 0.5, self_management: 0.75 },
    work_style: { structured_flexible: 0.3, detail_bigpicture: 0.4, independent_collaborative: 0.5, reflective_fast: 0.5, stability_novelty: 0.4 },
    environment: { indoor_outdoor: 0.1, team_solo: 0.5, structured_flexible_env: 0.3, quiet_active: 0.4, office_remote: 0.4, technical_social: 0.4, routine_varied: 0.5, high_low_pressure: 0.7 },
    education_ar: 'بكالوريوس في المالية أو المحاسبة', education_en: "Bachelor in Finance or Accounting",
    tasks_ar: ['تحليل البيانات المالية', 'بناء النماذج المالية', 'تقديم التوصيات الاستثمارية', 'إعداد التقارير المالية'],
    tasks_en: ['Analyzing financial data', 'Building financial models', 'Providing investment recommendations', 'Preparing financial reports'],
    pathways_ar: ['دراسة المالية', 'الحصول على شهادة CFA', 'اكتساب خبرة في التحليل المالي'],
    pathways_en: ['Study finance', 'Obtain CFA certification', 'Gain financial analysis experience'],
    related: ['accountant', 'data_analyst', 'management_consultant'],
  },
  {
    id: 'architect', title_ar: 'مهندس معماري', title_en: 'Architect',
    family_ar: 'العمارة والتصميم', family_en: 'Architecture & Design',
    riasec: { R: 0.7, I: 0.6, A: 0.85, S: 0.3, E: 0.4, C: 0.5 },
    work_values: { achievement: 0.8, working_conditions: 0.6, recognition: 0.8, relationships: 0.5, support: 0.5, independence: 0.7 },
    skills: { analytical: 0.8, communication: 0.7, organization: 0.8, digital_learning: 0.85, collaboration: 0.7, creativity: 0.9 },
    strengths: { thinking_learning: 0.8, achievement_perseverance: 0.8, influence_leadership: 0.5, relationships_cooperation: 0.6, self_management: 0.75 },
    work_style: { structured_flexible: 0.5, detail_bigpicture: 0.6, independent_collaborative: 0.5, reflective_fast: 0.4, stability_novelty: 0.6 },
    environment: { indoor_outdoor: 0.4, team_solo: 0.6, structured_flexible_env: 0.4, quiet_active: 0.5, office_remote: 0.3, technical_social: 0.4, routine_varied: 0.7, high_low_pressure: 0.5 },
    education_ar: 'بكالوريوس في الهندسة المعمارية', education_en: "Bachelor in Architecture",
    tasks_ar: ['تصميم المباني والمساحات', 'إعداد المخططات والرسومات', 'التعاون مع المقاولين', 'ضمان الامتثال للأنظمة'],
    tasks_en: ['Designing buildings and spaces', 'Preparing plans and drawings', 'Collaborating with contractors', 'Ensuring code compliance'],
    pathways_ar: ['دراسة الهندسة المعمارية', 'بناء معرض أعمال', 'اكتساب خبرة في التصميم'],
    pathways_en: ['Study architecture', 'Build a portfolio', 'Gain design experience'],
    related: ['engineer', 'graphic_designer', 'project_manager'],
  },
  {
    id: 'management_consultant', title_ar: 'مستشار إدارة', title_en: 'Management Consultant',
    family_ar: 'الاستشارات', family_en: 'Consulting',
    riasec: { R: 0.2, I: 0.7, A: 0.3, S: 0.6, E: 0.85, C: 0.6 },
    work_values: { achievement: 0.85, working_conditions: 0.5, recognition: 0.7, relationships: 0.7, support: 0.5, independence: 0.7 },
    skills: { analytical: 0.9, communication: 0.9, organization: 0.8, digital_learning: 0.7, collaboration: 0.85, creativity: 0.75 },
    strengths: { thinking_learning: 0.85, achievement_perseverance: 0.85, influence_leadership: 0.85, relationships_cooperation: 0.85, self_management: 0.85 },
    work_style: { structured_flexible: 0.5, detail_bigpicture: 0.8, independent_collaborative: 0.6, reflective_fast: 0.5, stability_novelty: 0.8 },
    environment: { indoor_outdoor: 0.2, team_solo: 0.7, structured_flexible_env: 0.4, quiet_active: 0.6, office_remote: 0.6, technical_social: 0.6, routine_varied: 0.9, high_low_pressure: 0.7 },
    education_ar: 'ماجستير إدارة أعمال (MBA) أو ما يعادله', education_en: 'MBA or equivalent',
    tasks_ar: ['تحليل المشكلات التنظيمية', 'تقديم حلول استراتيجية', 'إدارة مشاريع التغيير', 'تقديم العروض للعملاء'],
    tasks_en: ['Analyzing organizational problems', 'Providing strategic solutions', 'Managing change projects', 'Presenting to clients'],
    pathways_ar: ['دراسة إدارة الأعمال', 'اكتساب خبرة في مجال متخصص', 'تطوير مهارات التحليل والعرض'],
    pathways_en: ['Study business administration', 'Gain experience in a specialized field', 'Develop analysis and presentation skills'],
    related: ['project_manager', 'financial_analyst', 'sales_manager'],
  },
];

// ─── ACTION PLAN TEMPLATES ────────────────────────────────────────────────────
export const ACTION_PLAN_PHASES = [
  {
    id: 'explore', name: { ar: 'الاستكشاف', en: 'Explore' }, days: { ar: 'اليوم 1–30', en: 'Days 1–30' }, color: '#336fa3',
    tasks: {
      job_seeker: { ar: ['ابحث عن أفضل 3 مسارات مهنية تناسبك', 'تواصل مع 2–3 محترفين في مجالك', 'قارن مهاراتك الحالية بمتطلبات الأدوار', 'أكمل تجربة مهنية صغيرة'], en: ['Research your top 3 career paths', 'Connect with 2–3 professionals in your field', 'Compare your current skills with role requirements', 'Complete one small career experiment'] },
      student: { ar: ['ابحث عن أفضل 3 مسارات مهنية تناسبك', 'تواصل مع 2–3 خريجين في تخصصك', 'حدد المهارات المطلوبة لحقلك', 'شارك في نشاط مهني واحد'], en: ['Research your top 3 career paths', 'Connect with 2–3 alumni in your field', 'Identify skills needed for your field', 'Participate in one career activity'] },
      career_changer: { ar: ['ابحث عن أفضل 3 مسارات مهنية جديدة', 'تواصل مع 2–3 محترفين في المجال الجديد', 'قارن مهاراتك الحالية بالمتطلبات الجديدة', 'أكمل تجربة في المجال الجديد'], en: ['Research your top 3 new career paths', 'Connect with 2–3 professionals in the new field', 'Compare your skills with new requirements', 'Complete an experiment in the new field'] },
    },
  },
  {
    id: 'build', name: { ar: 'البناء', en: 'Build' }, days: { ar: 'اليوم 31–60', en: 'Days 31–60' }, color: '#05e1ae',
    tasks: {
      job_seeker: { ar: ['أكمل نشاط تعليمي مستهدف', 'ابنِ مشروعاً عملياً صغيراً', 'حدّث سيرتك الذاتية وملف LinkedIn', 'أنشئ أدلة على مهاراتك'], en: ['Complete one targeted learning activity', 'Build a small practical project', 'Update your CV and LinkedIn profile', 'Create evidence of your skills'] },
      student: { ar: ['أكمل دورة تدريبية في مهارة مطلوبة', 'ابنِ مشروعاً في مجالك', 'ابدأ بناء سيرتك الذاتية', 'شارك في مسابقة أو فعالية'], en: ['Complete a course in a required skill', 'Build a project in your field', 'Start building your CV', 'Participate in a competition or event'] },
      career_changer: { ar: ['أكمل تدريباً في مهارة جديدة', 'ابنِ مشروعاً في المجال الجديد', 'أعد صياغة سيرتك الذاتية', 'أنشئ معرض أعمال'], en: ['Complete training in a new skill', 'Build a project in the new field', 'Rewrite your CV', 'Create a portfolio'] },
    },
  },
  {
    id: 'launch', name: { ar: 'الانطلاق', en: 'Launch' }, days: { ar: 'اليوم 61–90', en: 'Days 61–90' }, color: '#4ca9fa',
    tasks: {
      job_seeker: { ar: ['قدّم على فرص مناسبة', 'ابنِ علاقات مهنية مستهدفة', 'حسّن معرض أعمالك', 'راجع تقدمك وحدّث خطتك'], en: ['Apply to suitable opportunities', 'Build targeted professional connections', 'Improve your portfolio', 'Review progress and update your plan'] },
      student: { ar: ['ابحث عن تدريب صيفي أو فرصة', 'وسّع شبكتك المهنية', 'وثّق إنجازاتك', 'خطط لخطوتك التالية'], en: ['Seek internship or opportunity', 'Expand your professional network', 'Document your achievements', 'Plan your next step'] },
      career_changer: { ar: ['قدّم على فرص في المجال الجديد', 'ابنِ علاقات في المجال المستهدف', 'وثّق خبراتك الجديدة', 'راجع وحدّث خطتك'], en: ['Apply to opportunities in the new field', 'Build relationships in the target field', 'Document your new experience', 'Review and update your plan'] },
    },
  },
];

// ─── COMPLETION TIPS ──────────────────────────────────────────────────────────
export const COMPLETION_TIPS = {
  ar: [
    'أكمل المقياس في مكان هادئ.',
    'أجب وفق سلوكك وتفضيلاتك الحقيقية.',
    'لا تجب وفق ما تراه مرغوباً اجتماعياً.',
    'لا تفكر كثيراً في كل إجابة.',
    'لا توجد إجابات صحيحة أو خاطئة إلا في أسئلة المهارات الموقفية.',
  ],
  en: [
    'Complete the assessment in a quiet place.',
    'Answer according to your real behavior and preferences.',
    'Do not answer according to what is socially desirable.',
    'Do not overthink each answer.',
    'There are no right or wrong answers unless the item is a situational skills question.',
  ],
};

// ─── DISCAIMER ────────────────────────────────────────────────────────────────
export const DISCLAIMER = {
  ar: 'هذا التقرير أداة إرشادية وتطويرية ولا يقدم تشخيصاً طبياً أو نفسياً أو توظيفياً. النتائج تعكس ميولك وتفضيلاتك بناءً على إجاباتك ويجب استخدامها كأداة مساعدة في اتخاذ قراراتك المهنية.',
  en: 'This report is a guidance and development tool and does not provide medical, psychological, or recruitment diagnosis. Results reflect your interests and preferences based on your responses and should be used as a decision-support tool.',
};