// Bilingual Content Library — OPTIVANCE Competency Assessment

export const BAND_CONFIG = {
  Strong:     { min: 80, color: '#05E1AE', bg: '#05e1ae12', border: '#05e1ae35', label: { ar: 'متقدم',        en: 'Strong'     } },
  Proficient: { min: 60, color: '#3a9abf', bg: '#3a9abf12', border: '#3a9abf35', label: { ar: 'كفء',          en: 'Proficient' } },
  Moderate:   { min: 40, color: '#F59E0B', bg: '#f59e0b12', border: '#f59e0b35', label: { ar: 'متوسط',        en: 'Moderate'   } },
  Critical:   { min: 0,  color: '#EF4444', bg: '#ef444412', border: '#ef444435', label: { ar: 'أولوية تطوير', en: 'Critical'   } },
};

export const getBand = (score) => {
  if (score >= 80) return 'Strong';
  if (score >= 60) return 'Proficient';
  if (score >= 40) return 'Moderate';
  return 'Critical';
};

export const OVERALL_SUMMARIES = {
  Strong: {
    ar: 'تعكس نتيجتك ملفًا مهنيًا متميزًا في معظم مجالات الكفاءة. نقاط قوتك واضحة ومتعددة، وهذا التقرير يساعدك على توجيه طاقتك نحو مستويات أعلى من الأثر والتأثير.',
    en: 'Your results reflect an outstanding professional profile across most competency areas. Your strengths are clear and multiple. This report helps you direct your energy toward higher levels of impact.',
  },
  Proficient: {
    ar: 'تمتلك أسسًا مهنية قوية مع فرص واضحة للتطوير. نتائجك تشير إلى إمكانات نمو حقيقية عند التركيز على المجالات الصحيحة.',
    en: 'You have strong professional foundations with clear development opportunities. Your results indicate real growth potential when focusing on the right areas.',
  },
  Moderate: {
    ar: 'تشير نتائجك إلى تفاوت في مستويات الكفاءة. بعض المجالات تُظهر قوة، وأخرى تستحق اهتمامًا أكبر. خطة تطوير مدروسة ستُحدث فرقًا واضحًا.',
    en: 'Your results indicate variability in competency levels. Some areas show strength while others deserve more attention. A thoughtful development plan will make a clear difference.',
  },
  Critical: {
    ar: 'تشير نتائجك إلى عدة أولويات تطوير مهمة. التعامل مع هذه المجالات بشكل منهجي ومتسق سيُحسّن أداءك المهني وأثرك بشكل ملموس.',
    en: 'Your results indicate several important development priorities. Addressing these areas systematically will noticeably improve your professional performance and impact.',
  },
};

export const LEVEL_LABELS = {
  operational:  { ar: 'تشغيلي',  en: 'Operational'  },
  specialist:   { ar: 'متخصص',   en: 'Specialist'   },
  supervisory:  { ar: 'إشرافي',  en: 'Supervisory'  },
  managerial:   { ar: 'مدير',    en: 'Manager'      },
  leadership:   { ar: 'قيادي',   en: 'Leadership'   },
};

export const DOMAINS = [
  {
    id: 'thought_analysis',
    name:        { ar: 'التفكير والتحليل',       en: 'Thought & Analysis' },
    description: { ar: 'يقيس قدرتك على التفكير النقدي وتحليل المواقف واتخاذ قرارات مدروسة.',
                   en: 'Measures critical thinking, situation analysis, and informed decision-making.' },
    sub_competencies: [
      { id: 'critical_thinking', name: { ar: 'التفكير النقدي',  en: 'Critical Thinking' } },
      { id: 'problem_solving',   name: { ar: 'حل المشكلات',     en: 'Problem Solving'   } },
      { id: 'decision_making',   name: { ar: 'اتخاذ القرارات',  en: 'Decision Making'   } },
    ],
    content: {
      Strong: {
        ar: { summary: 'تتمتع بقدرة تحليلية واضحة وأسلوب منهجي في اتخاذ القرارات. نتيجتك تعكس نضجًا فكريًا يدعم أداءك المهني.',
              strengths: ['تحليل المواقف بعمق قبل القرار', 'استخدام منطق واضح في حل المشكلات', 'الموازنة الفعالة بين الخيارات'],
              recommendations: ['استخدم أدوات تحليلية متقدمة كـ Root Cause وPESTLE', 'شارك منهجيتك التحليلية مع فريقك'],
              goals: { short: 'وثّق أسباب قراراتك المهمة هذا الأسبوع', mid: 'تبنَّ أداة تحليل متقدمة جديدة كل شهر', long: 'قُد ورشة تفكير تحليلي لفريقك' } },
        en: { summary: 'You demonstrate strong analytical capability and systematic decision-making. Your results reflect intellectual maturity.',
              strengths: ['Deep situational analysis before decisions', 'Clear logical reasoning in problem-solving', 'Effective balancing of options'],
              recommendations: ['Use advanced tools like Root Cause Analysis and PESTLE', 'Share your analytical methodology with your team'],
              goals: { short: 'Document reasoning behind key decisions this week', mid: 'Adopt one new advanced analytical tool each month', long: 'Lead an analytical thinking workshop for your team' } },
      },
      Proficient: {
        ar: { summary: 'لديك أساس تحليلي جيد مع فرص لتطوير منهجية أكثر انتظامًا في اتخاذ القرارات.',
              strengths: ['قدرة معقولة على التحليل', 'وعي بأهمية جمع المعلومات'],
              recommendations: ['استخدم قائمة تحقق قبل القرارات المهمة', 'تدرّب على تقنية 5 أسباب (5 Whys)'],
              goals: { short: 'ضع قائمة أسئلة تطرحها قبل كل قرار مهم', mid: 'طبّق منهجية تحليل مشكلة في موقف عمل حقيقي', long: 'ابنِ مرجعًا شخصيًا لأفضل أساليب اتخاذ القرار' } },
        en: { summary: 'You have a solid analytical foundation with opportunities for more systematic decision-making.',
              strengths: ['Reasonable analytical capability', 'Awareness of the importance of gathering information'],
              recommendations: ['Use a checklist before important decisions', 'Practice the 5 Whys technique'],
              goals: { short: 'Create a list of questions before each key decision', mid: 'Apply a full problem analysis in a real situation', long: 'Build a personal guide for best decision-making practices' } },
      },
      Moderate: {
        ar: { summary: 'تشير نتيجتك إلى فرص تطوير حقيقية في التفكير والتحليل. بناء منهجية واضحة سيُحسّن قراراتك بشكل ملموس.',
              strengths: ['الرغبة في التحسين والتطوير', 'الوعي الأساسي بأهمية التحليل'],
              recommendations: ['ابدأ بأداة بسيطة كقائمة الإيجابيات والسلبيات', 'اطلب توجيهًا من زميل خبير'],
              goals: { short: 'استخدم قائمة إيجابيات وسلبيات قبل قراراتك الأسبوعية', mid: 'احضر دورة في التفكير النقدي', long: 'ابنِ عادة مراجعة قراراتك والتعلم منها' } },
        en: { summary: 'Your results indicate real development opportunities in thinking and analysis. A clear methodology will noticeably improve your decisions.',
              strengths: ['Desire for improvement', 'Basic awareness of the importance of analysis'],
              recommendations: ['Start with a simple pros-and-cons list', 'Seek guidance from an experienced colleague'],
              goals: { short: 'Use a pros-and-cons list before weekly decisions', mid: 'Attend a critical thinking course', long: 'Build a habit of reviewing past decisions and learning from them' } },
      },
      Critical: {
        ar: { summary: 'هذا المجال يمثل أولوية تطوير رئيسية. تعزيز التفكير التحليلي سيُحدث أثرًا إيجابيًا واسعًا على قراراتك.',
              strengths: ['الاستعداد للتعلم والتغيير'],
              recommendations: ['لا تتخذ قرارات مهمة دون مراجعة المعلومات المتاحة', 'اعتمد نموذجًا بسيطًا لتقييم الخيارات', 'اطلب ملاحظات من مشرفك'],
              goals: { short: 'قبل أي قرار، اسأل: "ما المعلومات التي أحتاجها؟"', mid: 'استخدم Decision Matrix لتقييم الخيارات', long: 'احضر تدريبًا في اتخاذ القرارات وحل المشكلات' } },
        en: { summary: 'This is a key development priority. Strengthening analytical thinking will have a wide positive impact on your decisions.',
              strengths: ['Readiness to learn and change'],
              recommendations: ['Do not make key decisions without reviewing available information', 'Adopt a simple option evaluation model', 'Request feedback from your supervisor'],
              goals: { short: 'Before any decision, ask: "What information do I need?"', mid: 'Use a Decision Matrix to evaluate options regularly', long: 'Attend specialized training in decision-making and problem-solving' } },
      },
    },
  },
  {
    id: 'results_execution',
    name:        { ar: 'النتائج والتنفيذ',    en: 'Results & Execution' },
    description: { ar: 'يقيس قدرتك على تحديد الأولويات وإنجاز المهام وتحقيق الأهداف بفاعلية.',
                   en: 'Measures prioritization, task completion, and effective goal achievement.' },
    sub_competencies: [
      { id: 'goal_setting',   name: { ar: 'تحديد الأهداف',    en: 'Goal Setting'    } },
      { id: 'prioritization', name: { ar: 'إدارة الأولويات',  en: 'Prioritization'  } },
      { id: 'follow_through', name: { ar: 'إتمام المهام',      en: 'Follow-Through'  } },
    ],
    content: {
      Strong: {
        ar: { summary: 'تُظهر قدرة عالية على الإنجاز وتحقيق النتائج. نتيجتك تعكس انضباطًا في التنفيذ ووضوحًا في متابعة الأهداف.',
              strengths: ['تحديد الأهداف بوضوح', 'إدارة فعّالة للأولويات', 'متابعة دقيقة للمهام حتى اكتمالها'],
              recommendations: ['ابنِ نظامًا لتتبع الأهداف وقياس التقدم', 'علّم الآخرين أسلوبك في إدارة المهام'],
              goals: { short: 'راجع أهدافك الأسبوعية وقيّم تقدمك', mid: 'استخدم نظامًا لتتبع مشاريعك الكبيرة', long: 'قُد مشروعًا كاملاً من التخطيط إلى التسليم' } },
        en: { summary: 'You demonstrate a high ability to achieve results. Your results reflect execution discipline and clear goal follow-through.',
              strengths: ['Clear goal-setting ability', 'Effective priority management', 'Precise task tracking to completion'],
              recommendations: ['Build a system to track goals and measure progress', 'Teach others your execution approach'],
              goals: { short: 'Review weekly goals and assess progress', mid: 'Use a system to track major projects', long: 'Lead a full project from planning to delivery' } },
      },
      Proficient: {
        ar: { summary: 'لديك أداء جيد في تحقيق النتائج مع فرص لتطوير انتظامية أكثر في التنفيذ.',
              strengths: ['القدرة على إنجاز المهام الأساسية', 'الوعي بأهمية الأولويات'],
              recommendations: ['استخدم Eisenhower Matrix لتصنيف مهامك', 'ضع مواعيد نهائية واضحة لكل هدف'],
              goals: { short: 'رتّب مهامك اليومية حسب الأولوية', mid: 'طبّق أداة إدارة مشاريع بسيطة', long: 'بنِ نظام أولويات شخصي تستخدمه يوميًا' } },
        en: { summary: 'You have good results achievement with opportunities for more consistent execution.',
              strengths: ['Ability to complete core tasks', 'Awareness of the importance of priorities'],
              recommendations: ['Use the Eisenhower Matrix to classify tasks', 'Set clear deadlines for each goal'],
              goals: { short: 'Sort your daily tasks by priority', mid: 'Apply a simple project management tool', long: 'Build a personal priority system you use daily' } },
      },
      Moderate: {
        ar: { summary: 'تشير نتيجتك إلى فرص لتحسين قدرتك على التنفيذ ومتابعة الأهداف.',
              strengths: ['الرغبة في الإنجاز', 'الالتزام الأساسي بالعمل'],
              recommendations: ['استخدم قائمة مهام يومية بسيطة', 'حدّد ثلاثة أهداف أسبوعية وتتبعها'],
              goals: { short: 'ضع قائمة مهام يومية واتبعها', mid: 'تتبع أهدافك الأسبوعية وسجّل التقدم', long: 'طوّر نظامًا شخصيًا لإدارة الأهداف' } },
        en: { summary: 'Your results indicate opportunities to improve execution capability and goal follow-through.',
              strengths: ['Desire to achieve', 'Basic work commitment'],
              recommendations: ['Use a simple daily task list', 'Set three weekly goals and track progress'],
              goals: { short: 'Create a daily task list and follow it', mid: 'Track weekly goals and record progress', long: 'Develop a personal goal management system' } },
      },
      Critical: {
        ar: { summary: 'هذا المجال أولوية تطوير عالية. تحسين التنفيذ ومتابعة الأهداف سيُحسّن أداءك العام بشكل ملموس.',
              strengths: ['الاستعداد للتعلم'],
              recommendations: ['ابدأ بإنجاز مهمة صغيرة واحدة كاملة يوميًا', 'اطلب مساعدة مشرفك في تحديد أولوياتك', 'تجنب تعدد المهام وركّز على شيء واحد'],
              goals: { short: 'أنهِ مهمة واحدة كاملة كل يوم', mid: 'تعلّم تقنية Time Blocking', long: 'احضر تدريبًا في إدارة الوقت والإنتاجية' } },
        en: { summary: 'This is a high development priority. Improving execution and goal follow-through will noticeably enhance overall performance.',
              strengths: ['Readiness to learn'],
              recommendations: ['Start by completing one small task fully each day', 'Ask your supervisor to help prioritize', 'Avoid multitasking — focus on one thing at a time'],
              goals: { short: 'Complete one full task each day', mid: 'Learn the Time Blocking technique', long: 'Attend training in time management and personal productivity' } },
      },
    },
  },
  {
    id: 'people_collaboration',
    name:        { ar: 'الأشخاص والتعاون',    en: 'People & Collaboration' },
    description: { ar: 'يقيس قدرتك على التواصل الفعّال وبناء علاقات العمل والتعاون مع الآخرين.',
                   en: 'Measures effective communication, working relationship building, and collaboration.' },
    sub_competencies: [
      { id: 'communication',       name: { ar: 'التواصل الفعّال',  en: 'Effective Communication' } },
      { id: 'teamwork',            name: { ar: 'العمل الجماعي',    en: 'Teamwork'                } },
      { id: 'conflict_resolution', name: { ar: 'إدارة الخلافات',   en: 'Conflict Resolution'     } },
    ],
    content: {
      Strong: {
        ar: { summary: 'تتمتع بمهارات تواصل وتعاون متطورة. قدرتك على بناء علاقات عمل فعّالة تُعدّ نقطة قوة رئيسية.',
              strengths: ['تواصل واضح ومؤثر', 'بناء علاقات عمل متينة', 'إدارة إيجابية للخلافات'],
              recommendations: ['تبنَّ دور الميسّر أو المرشد للآخرين', 'شارك مهاراتك في التواصل مع فريقك'],
              goals: { short: 'أعطِ تغذية راجعة بناءة لزميل أسبوعيًا', mid: 'قُد اجتماعًا أو مبادرة تعاونية', long: 'طوّر برنامجًا لتحسين التواصل في فريقك' } },
        en: { summary: 'You possess advanced communication and collaboration skills. Your ability to build effective working relationships is a key strength.',
              strengths: ['Clear and impactful communication', 'Strong working relationship building', 'Positive conflict management'],
              recommendations: ['Take on a facilitator or mentor role', 'Share your communication skills with your team'],
              goals: { short: 'Give constructive feedback to a colleague weekly', mid: 'Lead a meeting or collaborative initiative', long: 'Develop a communication improvement program for your team' } },
      },
      Proficient: {
        ar: { summary: 'لديك مهارات تواصل وتعاون جيدة مع فرص لتعميق علاقاتك المهنية.',
              strengths: ['تواصل معقول مع الآخرين', 'قدرة على العمل ضمن الفريق'],
              recommendations: ['مارس الاستماع الفعّال أثناء الاجتماعات', 'اطلب تغذية راجعة حول أسلوب تواصلك'],
              goals: { short: 'ركّز على الاستماع الكامل دون مقاطعة في اجتماع يوميًا', mid: 'طوّر علاقات أعمق مع زميلين من خارج فريقك', long: 'احضر ورشة في مهارات التواصل' } },
        en: { summary: 'You have good communication skills with opportunities to deepen professional relationships.',
              strengths: ['Reasonable communication with others', 'Ability to work within a team'],
              recommendations: ['Practice active listening during meetings', 'Seek feedback on your communication style'],
              goals: { short: 'Practice full listening without interruption in one meeting daily', mid: 'Build deeper relationships with two colleagues outside your team', long: 'Attend a communication skills workshop' } },
      },
      Moderate: {
        ar: { summary: 'تشير نتيجتك إلى أن تطوير مهارات التواصل والتعاون سيُحسّن تجربتك المهنية وأثرك على الآخرين.',
              strengths: ['الرغبة في التواصل', 'الالتزام الأساسي بمتطلبات العمل'],
              recommendations: ['مارس الاستماع: اسمع للفهم، لا للرد فقط', 'ابحث عن فرصة للتعاون في مشروع خارج مهامك'],
              goals: { short: 'تواصل بشكل إيجابي مع زميل واحد جديد هذا الأسبوع', mid: 'شارك في مشروع مشترك مع فريق آخر', long: 'تعلّم أسلوب التغذية الراجعة الإيجابية وطبّقه' } },
        en: { summary: 'Your results indicate that developing communication and collaboration will noticeably improve your professional experience.',
              strengths: ['Desire to communicate', 'Basic work commitment'],
              recommendations: ['Practice active listening: hear to understand, not just to respond', 'Look for collaboration opportunities outside your usual scope'],
              goals: { short: 'Engage positively with one new colleague this week', mid: 'Participate in a joint project with another team', long: 'Learn and apply the positive feedback approach' } },
      },
      Critical: {
        ar: { summary: 'تشير نتيجتك إلى أن هذا المجال أولوية تطوير. تحسين التواصل والتعاون سينعكس إيجابًا على علاقاتك ومسيرتك المهنية.',
              strengths: ['الاستعداد للتطور والتحسين'],
              recommendations: ['ابدأ بمحادثات قصيرة بناءة مع زملائك', 'تجنب الانعزال قدر الإمكان', 'اطلب feedback من شخص موثوق'],
              goals: { short: 'تواصل مع زميل واحد يوميًا بشكل إيجابي', mid: 'اشترك في مبادرة فريق وساهم فيها', long: 'احضر تدريبًا في مهارات التواصل وبناء العلاقات' } },
        en: { summary: 'Your results indicate this is a development priority. Improving communication and collaboration will positively impact your relationships and career.',
              strengths: ['Readiness for growth and improvement'],
              recommendations: ['Start with short, constructive conversations with colleagues', 'Avoid isolation as much as possible', 'Ask a trusted person for feedback'],
              goals: { short: 'Connect with one colleague daily in a positive way', mid: 'Join a team initiative and contribute actively', long: 'Attend training in effective communication and relationship-building' } },
      },
    },
  },
  {
    id: 'self_leadership',
    name:        { ar: 'القيادة الذاتية والنمو',    en: 'Self-Leadership & Growth' },
    description: { ar: 'يقيس الوعي الذاتي والمبادرة الشخصية والتوجه نحو التعلم والتطور المستمر.',
                   en: 'Measures self-awareness, personal initiative, and continuous learning orientation.' },
    sub_competencies: [
      { id: 'self_awareness',       name: { ar: 'الوعي الذاتي',       en: 'Self-Awareness'       } },
      { id: 'initiative',           name: { ar: 'المبادرة الشخصية',   en: 'Personal Initiative'  } },
      { id: 'learning_orientation', name: { ar: 'التوجه للتعلم',      en: 'Learning Orientation' } },
    ],
    content: {
      Strong: {
        ar: { summary: 'تتمتع بوعي ذاتي عالٍ ومبادرة شخصية واضحة. توجهك للتعلم المستمر يجعلك نموذجًا يُحتذى.',
              strengths: ['وعي ذاتي بنقاط القوة والتطوير', 'مبادرة شخصية في التعلم', 'توجه إيجابي نحو التحدي'],
              recommendations: ['كن مرشدًا لمن هم في بداياتهم المهنية', 'شارك تجاربك في النمو مع مجتمعك المهني'],
              goals: { short: 'ضع هدف تعلّم شهريًا وتتبع تقدمك', mid: 'كن مرشدًا لزميل أقل خبرة', long: 'بنِ مسار تطوير شخصي يغطي السنوات الثلاث القادمة' } },
        en: { summary: 'You demonstrate high self-awareness and clear personal initiative. Your orientation toward continuous learning makes you a role model.',
              strengths: ['Clear self-awareness of strengths', 'Personal initiative in learning', 'Positive orientation toward challenge'],
              recommendations: ['Become a mentor for early-career professionals', 'Share your growth experiences with your professional community'],
              goals: { short: 'Set a monthly learning goal and track progress', mid: 'Become a mentor to a less experienced colleague', long: 'Build a personal development path covering the next three years' } },
      },
      Proficient: {
        ar: { summary: 'لديك وعي ذاتي جيد وتوجه للتطوير مع فرص لتعميق مبادرتك.',
              strengths: ['وعي بنقاط القوة الشخصية', 'استعداد للتطوير والتعلم'],
              recommendations: ['ضع خطة تطوير شخصية واضحة', 'اطلب ملاحظات منتظمة من مشرفك'],
              goals: { short: 'اكتب ثلاث نقاط قوة وثلاثة مجالات تطوير شخصية', mid: 'ضع خطة تطوير لثلاثة أشهر', long: 'اعثر على مرشد مهني وانخرط معه بانتظام' } },
        en: { summary: 'You have good self-awareness with opportunities to deepen personal initiative.',
              strengths: ['Awareness of personal strengths', 'Readiness for development and learning'],
              recommendations: ['Create a clear personal development plan', 'Request regular feedback from your supervisor or mentor'],
              goals: { short: 'Write three personal strengths and three development areas', mid: 'Create a three-month development plan', long: 'Find a professional mentor and engage with them regularly' } },
      },
      Moderate: {
        ar: { summary: 'تشير نتيجتك إلى أن تطوير الوعي الذاتي والمبادرة سيُحسّن مسيرتك المهنية بشكل ملحوظ.',
              strengths: ['الرغبة الأساسية في التحسين', 'الانفتاح على الملاحظات'],
              recommendations: ['خصّص 10 دقائق أسبوعيًا للتأمل في أدائك', 'اقرأ كتابًا متعلقًا بمجالك كل شهر'],
              goals: { short: 'اكتب يوميًا درسًا واحدًا تعلمته في العمل', mid: 'خصّص ساعة أسبوعيًا للتطوير الذاتي', long: 'احضر دورة في الوعي الذاتي أو التطوير القيادي' } },
        en: { summary: 'Your results indicate that developing self-awareness and initiative will noticeably improve your career journey.',
              strengths: ['Basic desire for improvement', 'Openness to feedback and guidance'],
              recommendations: ['Dedicate 10 minutes weekly to reflecting on your performance', 'Read one book related to your field each month'],
              goals: { short: 'Write one lesson learned at work each day', mid: 'Dedicate one hour weekly to intentional self-development', long: 'Attend a course in self-awareness or leadership development' } },
      },
      Critical: {
        ar: { summary: 'بناء الوعي الذاتي والمبادرة الشخصية هو أساس أي نمو مهني حقيقي. هذا المجال يستحق اهتمامًا أوليًا.',
              strengths: ['الاستعداد للتغيير'],
              recommendations: ['ابدأ بسؤال نفسك: "ما الذي أفعله جيدًا اليوم؟"', 'اطلب ملاحظة بناءة من شخص تثق به', 'لا تنتظر الفرص، ابحث عنها بنشاط'],
              goals: { short: 'اسأل زميلًا موثوقًا عن نقطة قوة وفرصة تطوير فيك', mid: 'حدّد هدفًا للتعلم الذاتي وتتبعه أسبوعيًا', long: 'ابنِ خطة شخصية لتطوير مهاراتك على مدى 6 أشهر' } },
        en: { summary: 'Building self-awareness and personal initiative is the foundation of any real professional growth. This area deserves priority attention.',
              strengths: ['Readiness for change'],
              recommendations: ['Start by asking yourself: "What am I doing well today?"', 'Ask someone you trust for constructive feedback', 'Don\'t wait for opportunities — actively seek them'],
              goals: { short: 'Ask a trusted colleague for one strength and one development opportunity', mid: 'Identify a self-learning goal and track it weekly', long: 'Build a personal plan to develop your skills over 6 months' } },
      },
    },
  },
  {
    id: 'customer_value',
    name:        { ar: 'قيمة العميل وأصحاب المصلحة',    en: 'Customer & Stakeholder Value' },
    description: { ar: 'يقيس قدرتك على فهم احتياجات العملاء وأصحاب المصلحة وتقديم قيمة مضافة.',
                   en: 'Measures understanding of customer and stakeholder needs and delivering added value.' },
    sub_competencies: [
      { id: 'customer_focus',   name: { ar: 'التركيز على العميل',    en: 'Customer Focus'        } },
      { id: 'stakeholder_mgmt', name: { ar: 'إدارة أصحاب المصلحة',  en: 'Stakeholder Management'} },
      { id: 'service_quality',  name: { ar: 'جودة الخدمة',           en: 'Service Quality'       } },
    ],
    content: {
      Strong: {
        ar: { summary: 'تُظهر توجهًا واضحًا نحو العميل. قدرتك على خلق قيمة مضافة تجعلك عنصرًا محوريًا في أي فريق.',
              strengths: ['فهم عميق لاحتياجات العملاء', 'بناء علاقات إيجابية مع أصحاب المصلحة', 'تقديم خدمة تتجاوز التوقعات'],
              recommendations: ['طوّر آليات قياس رضا العملاء', 'شارك أفضل ممارساتك مع فريقك'],
              goals: { short: 'اسأل عميلًا عن تجربته مع خدماتك', mid: 'صمّم آلية لجمع تغذية راجعة منتظمة', long: 'قُد مبادرة لتحسين تجربة العميل في فريقك' } },
        en: { summary: 'You demonstrate a clear customer orientation. Your ability to create added value makes you a pivotal element in any team.',
              strengths: ['Deep customer needs understanding', 'Positive stakeholder relationship building', 'Service delivery exceeding expectations'],
              recommendations: ['Develop customer satisfaction measurement mechanisms', 'Share your best practices with your team'],
              goals: { short: 'Ask a customer about their experience with your services', mid: 'Design a regular customer feedback mechanism', long: 'Lead a customer experience improvement initiative' } },
      },
      Proficient: {
        ar: { summary: 'لديك توجه جيد نحو العميل مع فرص لتعميق فهمك لأصحاب المصلحة.',
              strengths: ['وعي بأهمية رضا العميل', 'التزام بمتطلبات الجودة الأساسية'],
              recommendations: ['تعرّف على جميع أصحاب المصلحة وما يهمهم', 'اسأل العملاء عن توقعاتهم بشكل استباقي'],
              goals: { short: 'اسأل عميلًا: "ما الذي يمكنني تحسينه؟"', mid: 'راجع دوريًا متطلبات أصحاب المصلحة', long: 'طوّر خريطة لأصحاب المصلحة واستراتيجية للتفاعل' } },
        en: { summary: 'You have a good customer orientation with opportunities to deepen stakeholder understanding.',
              strengths: ['Awareness of the importance of customer satisfaction', 'Adherence to basic quality standards'],
              recommendations: ['Identify all stakeholders and what matters to them', 'Ask customers about their expectations proactively'],
              goals: { short: 'Ask one customer: "What can I improve?"', mid: 'Conduct regular stakeholder expectation reviews', long: 'Develop a stakeholder map and engagement strategy' } },
      },
      Moderate: {
        ar: { summary: 'تشير نتيجتك إلى فرص لتعزيز توجهك نحو العميل وقدرتك على إدارة أصحاب المصلحة.',
              strengths: ['الالتزام الأساسي بمتطلبات العمل', 'الرغبة في تقديم أفضل ما يمكن'],
              recommendations: ['ابدأ بسؤال: "من هم المستفيدون من عملي؟"', 'تعلّم كيف تدير توقعات الآخرين استباقيًا'],
              goals: { short: 'اكتب قائمة بالأشخاص المستفيدين من عملك', mid: 'اجمع تغذية راجعة من مستفيد واحد شهريًا', long: 'احضر دورة في خدمة العملاء أو إدارة أصحاب المصلحة' } },
        en: { summary: 'Your results indicate opportunities to strengthen customer orientation and stakeholder management.',
              strengths: ['Basic work commitment', 'Desire to deliver the best possible work'],
              recommendations: ['Start with: "Who benefits from my work?"', 'Learn how to proactively manage others\' expectations'],
              goals: { short: 'Write a list of your work beneficiaries', mid: 'Collect feedback from at least one beneficiary monthly', long: 'Attend a course in customer service or stakeholder management' } },
      },
      Critical: {
        ar: { summary: 'هذا المجال فرصة تطوير مهمة. تحسين قدرتك على فهم الآخرين وتقديم القيمة سيُحسّن علاقاتك المهنية.',
              strengths: ['الاستعداد للتحسين'],
              recommendations: ['اسأل مشرفك: من هم أهم المستفيدين من عملي؟', 'ركّز على إنجاز مهامك بجودة عالية', 'ابحث عن نموذج إيجابي في خدمة العملاء'],
              goals: { short: 'تعرّف على توقعات مستفيد واحد هذا الأسبوع', mid: 'سجّل ملاحظاتك حول ما يحتاجه المستفيدون', long: 'احضر تدريبًا في إدارة العلاقات وخدمة العملاء' } },
        en: { summary: 'This is an important development opportunity. Improving your ability to understand others and deliver value will enhance professional relationships.',
              strengths: ['Readiness for improvement'],
              recommendations: ['Ask your supervisor who the key beneficiaries of your work are', 'Focus on high-quality task completion', 'Look for a positive customer service role model'],
              goals: { short: 'Learn one beneficiary\'s expectations this week', mid: 'Record observations about what your beneficiaries need', long: 'Attend training in relationship management and customer service' } },
      },
    },
  },
  {
    id: 'digital_compliance',
    name:        { ar: 'الرقمية والاستدامة والامتثال',    en: 'Digital, Sustainability & Compliance' },
    description: { ar: 'يقيس مدى توافقك مع المتطلبات الرقمية والمؤسسية والاستدامة في بيئة العمل.',
                   en: 'Measures alignment with digital, organizational, and sustainability requirements.' },
    sub_competencies: [
      { id: 'digital_literacy', name: { ar: 'الكفاءة الرقمية',   en: 'Digital Literacy'          } },
      { id: 'compliance',       name: { ar: 'الامتثال المؤسسي',  en: 'Organizational Compliance' } },
      { id: 'sustainability',   name: { ar: 'التفكير المستدام',   en: 'Sustainability Thinking'   } },
    ],
    content: {
      Strong: {
        ar: { summary: 'تُظهر مستوى عاليًا من الكفاءة الرقمية والالتزام المؤسسي. توجهك المستدام يعكس وعيًا مهنيًا ناضجًا.',
              strengths: ['كفاءة رقمية متطورة', 'التزام راسخ بالامتثال والأنظمة', 'وعي بأهمية الاستدامة'],
              recommendations: ['كن رائدًا في تبني التقنيات الجديدة في فريقك', 'شارك خبرتك الرقمية مع زملائك'],
              goals: { short: 'اكتشف تقنية جديدة وشارك ما تعلمته', mid: 'قُد مبادرة لتحسين العمليات الرقمية', long: 'طوّر خطة لرفع الكفاءة الرقمية في وحدتك' } },
        en: { summary: 'You demonstrate a high level of digital competence and compliance commitment. Your sustainable orientation reflects mature professional awareness.',
              strengths: ['Advanced digital competence', 'Strong compliance commitment', 'Sustainability awareness'],
              recommendations: ['Champion the adoption of new technologies in your team', 'Share your digital expertise with colleagues'],
              goals: { short: 'Discover a new technology and share what you learned', mid: 'Lead a digital process improvement initiative', long: 'Develop a plan to raise digital competence in your unit' } },
      },
      Proficient: {
        ar: { summary: 'لديك مستوى جيد من الكفاءة الرقمية مع فرص لتطوير توجهك المستدام.',
              strengths: ['مستوى جيد من الكفاءة الرقمية', 'التزام بالمتطلبات الأساسية'],
              recommendations: ['خصّص وقتًا أسبوعيًا لاستكشاف أدوات رقمية جديدة', 'راجع سياسات الامتثال الأساسية'],
              goals: { short: 'استكشف أداة رقمية جديدة هذا الشهر', mid: 'أكمل دورة في أمن المعلومات أو الامتثال', long: 'طوّر كفاءتك في مجال رقمي متخصص' } },
        en: { summary: 'You have a good level of digital competence with opportunities to develop sustainable orientation.',
              strengths: ['Good level of digital competence', 'Adherence to basic requirements'],
              recommendations: ['Dedicate weekly time to exploring new digital tools', 'Review basic compliance policies'],
              goals: { short: 'Explore a new digital tool this month', mid: 'Complete a course in information security or compliance', long: 'Develop competence in a specialized digital area' } },
      },
      Moderate: {
        ar: { summary: 'تشير نتيجتك إلى فرص لتعزيز كفاءتك الرقمية ووعيك بمتطلبات الامتثال والاستدامة.',
              strengths: ['الاستعداد للتعلم والتكيف', 'الوعي الأساسي بأهمية التقنية'],
              recommendations: ['تعلّم استخدام أدوات العمل الرئيسية بكفاءة أعلى', 'تعرّف على سياسات الامتثال الأساسية'],
              goals: { short: 'تعلّم ميزة جديدة في برنامج تستخدمه يوميًا', mid: 'اقرأ دليل الامتثال في مؤسستك', long: 'احضر دورة في الكفاءة الرقمية' } },
        en: { summary: 'Your results indicate opportunities to enhance digital competence and compliance awareness.',
              strengths: ['Readiness to learn and adapt', 'Basic technology awareness'],
              recommendations: ['Learn to use your main work tools more efficiently', 'Familiarize yourself with basic compliance policies'],
              goals: { short: 'Learn a new feature in a daily-use program', mid: 'Read the compliance guide in your organization', long: 'Attend a digital competence course' } },
      },
      Critical: {
        ar: { summary: 'هذا المجال أولوية تطوير في ظل متطلبات بيئة العمل الرقمية المتسارعة.',
              strengths: ['الاستعداد للتعلم والتطور'],
              recommendations: ['ابدأ بإتقان الأدوات الأساسية التي تستخدمها يوميًا', 'اسأل مشرفك عن السياسات الأساسية', 'تعلّم مفاهيم الأمن الرقمي الأساسية'],
              goals: { short: 'تعلّم وظيفة واحدة جديدة في تقنية يومية', mid: 'أكمل دورة تأسيسية في الكفاءة الرقمية', long: 'احضر تدريبًا في الامتثال المؤسسي والتحول الرقمي' } },
        en: { summary: 'This is a development priority given the rapidly evolving digital work environment.',
              strengths: ['Readiness to learn and grow'],
              recommendations: ['Start by mastering the basic tools you use daily', 'Ask your supervisor about key policies you should know', 'Learn basic digital security concepts'],
              goals: { short: 'Learn one new function in a daily-use technology', mid: 'Complete a foundational digital competence course', long: 'Attend training in organizational compliance and digital transformation' } },
      },
    },
  },
];